#!/bin/bash

script/setup

version=$(grep -o '"version": *"[^"]*"' package.json | awk -F '"' '{print $4}')

git tag -a "$version" -m "Release $version" && git push origin "$version"

docker-compose run --rm -T --name simple-service-authorizer-publishing app npm publish
