#!/bin/bash

docker run \
  --interactive --tty --rm \
  --env CODECLIMATE_CODE="$PWD/src" \
  --volume "$PWD/src":/code \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume /tmp/cc:/tmp/cc \
  codeclimate/codeclimate analyze
